wam_v:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Controllers ------------------------------------------------
  right_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_motor_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  ship_controller:
    type: ship_controller/ShipController
    right_motor: right_motor_joint
    left_motor: left_motor_joint
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.5  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.1  # m/s^2
        min_acceleration       : -0.1 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.3  # rad/s
        min_velocity           : -0.3
        has_acceleration_limits: true
        max_acceleration       : 0.1  # rad/s^2
        min_acceleration       : 0.1
